name: Laravel-CI

on:
    push:
        branches:
            - main
            - develop
            - '*.x'
    pull_request:

    schedule:
        - cron: '0 0 * * *'

permissions:
    contents: read

jobs:
    Check-Code-Styling:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Fix PHP code style issues
              uses: aglipanci/laravel-pint-action@1.0.0

            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - name: Install dependencies
              run: npm ci
            - name: Format code
              run: npm run format

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Fix styling
    Build-Tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [8.2]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-interaction --no-progress
            - name: Copy environment file
              run: cp .env.example .env

            - name: Generate app key
              run: php artisan key:generate

            - name: Install Npm dependencies
              run: npm install
            - name: Build Inertia
              run: npm run build

            - name: Execute tests
              run: vendor/bin/phpunit
